name: Build, Push, and Deploy to EKS

on:
  push:
    branches:
      - main
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug GitHub Context
      run: |
        echo "GITHUB_REF=${GITHUB_REF}"
        echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"


    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::225989347065:role/oidc_github
        role-session-name: samplerolesession
        aws-region: ap-southeast-2

    # Authenticate Docker to ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 225989347065.dkr.ecr.ap-southeast-2.amazonaws.com

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t hello-world-image .

    # Tag the Docker image
    - name: Tag Docker image
      run: |
        docker tag hello-world-image:latest 225989347065.dkr.ecr.ap-southeast-2.amazonaws.com/hello-world

    # Push the Docker image to ECR
    - name: Push Docker image to Amazon ECR
      run: |
        docker push 225989347065.dkr.ecr.ap-southeast-2.amazonaws.com/hello-world

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
    # Set up AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Update kubeconfig
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ap-southeast-2 --name eks-testing

    # Deploy to EKS
    - name: Apply Kubernetes manifest
      run: |
        pwd
        ls
        kubectl apply -f deployment.yaml
        kubectl get services
        kubectl get pods -o wide
        kubectl get svc
        kubectl get deployments
        kubectl describe svc hello-world
